CREATE TABLE IF NOT EXISTS cats (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                TEXT NOT NULL,
  years_experience    INT  NOT NULL DEFAULT 0 CHECK (years_experience BETWEEN 0 AND 60),
  breed               TEXT NOT NULL,
  salary              NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (salary >= 0),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);